run_test error1
run_test if_sub
run_test if_sub_embed
run_test simple_sub1
run_test simple_sub2
run_test weird_sub
#run_test sub_hard_block
#run_test ultra_hell_sub
run_test error2
run_test if_sub1
run_test simple_sub
run_test sub_embed
run_test error3
run_test error4
run_test sub2.test
run_test sub3.test
run_test sub4.test
run_test sub5.test
run_test sub6.test
run_test sub7.test
run_test sub8.test
run_test sub9.test
run_test sub10.test
run_test sub11.test
run_test sub12.test
run_test sub13.test
run_test sub14.test
run_test sub15.test
run_test sub16.test
#run_test sub17.test
run_test sub_sub1.test
